# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae4240a0d37673b955040b3f1202dc8a2bbbfa015dc5346ebe041ef8f24c6245fc646ef7341322043c52d600be05be7e8dd01c425655d5f7f987d88e6c36d446

test:
  secret_key_base: 214c27cd3109e51c6875fac04c36ac3c7372bb73d7b081bf91196b57ba0e9b5a601aa7d15b13aa986fe7a14f1ea125579cce9eeb198126f7f344f599270881d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
